trigger:
- none

pool:
  name: Self-Hosted

stages:
  - stage: 'POC'

    jobs:
    - deployment: 'Build'
      environment: 'POC'
      strategy:
        runOnce:
          deploy:
            steps:

              - checkout: self
                submodules: true
              
              - task: Gradle@3
                inputs:
                  gradleWrapperFile: 'gradlew'
                  workingDirectory: '$(Build.SourcesDirectory)/android'
                  tasks: 'build'
                  publishJUnitResults: false
                  javaHomeOption: 'JDKVersion'
                  sonarQubeRunAnalysis: false
                  spotBugsAnalysis: false
              
